### PR TITLE
Move the verif files around to have less DUT and use the -top flag to…

### LINKED ISSUE #442: change the directory structure in the verification
The directory structure in the verification is a little strange and i think it can be improved.

The idea is that we will have the same main directory as the RTL.
Meaning the content of the "verif/cache" should be moved into mem_ss
and the content of "verif/router" should be moved into fabric.

Then the list.f file should be merged into a single file - but keep many different "_tb" files that can be used using the "-top" option in the compilation command.

This change will need carful merging in the list.f files, in the include and functions, and the workflow sanity command ext

### PR DESCRIPTION
**Pull request by amichai-bd**
… run it correctly the subIP

issue closes #442

### CODE REVIEW

**Comment by roman012285** [comment]
image
Some errors while opening `gui_build.py`. I am not sure what it does so Iam not trying to fix that

**Comment by amichai-bd** [comment]
@roman012285 - FYI i fixed it.
There was a file that was generated when running the PP.
It was called __pycache__ - a file that is generated when you import local python scripts.
I added a flag so it wont be generated anymore.

I will note that It was part of the gitignore - but when I moved things around it was committed by accident. 
I fixed the gitignore - and also fixed the PP scripts so it wont create this file anymore

**Comment by roman012285** [comment]
I saw that commit and the files you changed. Because there was directories that I never worked with them, than I planned to ask you about ot later. If we talking about it know so maybe its tine to ask what have you done there and what is PP?

**Comment by amichai-bd** [comment]
The PP is a Post-Procces script.

The way the student wrote it he had 2 files.
1) ref_orderer.py
2) mem_ss_pp.py

The "mem_ss_pp.py" is what called buy the build when adding the -pp flag.
In the beginning of the "mem_ss_pp.py" there was an import:
``` python
import ref_orderer
```

When ChatGPT explained that the python will try to optimize "local imports" by creating a "pycache" to allow reuse of the imports.

I did not like this generation so i add this line before the import:
``` python
sys.dont_write_bytecode = True
import ref_orderer
```

Which will make sure there will be no pycache generation when importing a local Python script.

I guess there is a simpler solution - just remove the "ref_orederer.py" and write the function in the original "mem_ss_pp"

I think i will do that now

**Comment by roman012285** [comment]
Thanks for the explanation.I understand the logic behind it

**Pull request merged**
